### PR TITLE
Update fabric Api spec from v4.7 to v4.9

### PR DESCRIPTION
**Pull request by manu-equinix**
Includes changes from the new Fabric API spec update which can be found here - https://app.swaggerhub.com/apis/equinix-api/fabric/4.9

Developer documentation(includes release notes for Aug 2023 release): https://developer.equinix.com/docs?page=/dev-docs/fabric/overview

All the Fabric gateway based APIs have changed to Fabric cloud router including some parameters listed below.

For example: 
fabric/v4/gateways -> fabric/v4/routers

**Summary of key changes:**

API | Changed Object | Existing Value | New Value
-- | -- | -- | --
Cloud Router | Path Parameter | gatewayId | routerId
  | Router type | XF_GATEWAY | XF_ROUTER
  | Path parameter | gatewayPackageCode | routerPackageCode
  | Router Package type | GATEWAY_PACKAGE | ROUTER_PACKAGE
Event | Response entity | gateway | router
  | Query Parameter | gatewayId | routerId
  | Router type | XF_GATEWAY | XF_ROUTER
Connections API | Access point schema | gateway | router
  | Access point type | GW (other type: VD, VG, SP, IGW, COLO, etc) | CLOUD_ROUTER
Prices API | type | FABRIC_GATEWAY_PRODUCT | CLOUD_ROUTER_PRODUCT

<br class="Apple-interchange-newline">

### CODE REVIEW

**Comment by ctreatma** [comment]
The test workflow is changing, but I think it's just because of an uncommited generate change to the `.gitignore` file.  Could you make sure to regenerate the code locally and commit that file?

**Comment by manu-equinix** [comment]
@ctreatma Added a link to the swaggerhub API spec release as well as release notes. Also, fixed the workflows failure with a new build/push.

**Comment by ctreatma** [comment]
While the API may not be changing much, all of these renames are a breaking change for the SDK.  Since this SDK is still `v0.x`, it's fine to introduce these changes in the next release without bumping the major version (so: `v0.5.0` => `v0.6.0` is OK here).  That said: when you cut the SDK release that includes these changes, you will need to call out that the product has been renamed, and that many of the types defined in the SDK have been renamed with it.

**Comment by manu-equinix** [comment]
> While the API may not be changing much, all of these renames are a breaking change for the SDK. Since this SDK is still `v0.x`, it's fine to introduce these changes in the next release without bumping the major version (so: `v0.5.0` => `v0.6.0` is OK here). That said: when you cut the SDK release that includes these changes, you will need to call out that the product has been renamed, and that many of the types defined in the SDK have been renamed with it.

@ctreatma Added a summary of changes to the description. Please check and approve if it looks good.

**Review by displague — APPROVED** [review]

**Pull request merged**
