### PR TITLE
Fabric 4.7

### PR DESCRIPTION
**Pull request by displague**
Includes changes from https://github.com/manu-equinix/fabric-go/tree/update-spec-4.7 by @manu-equinix 

Reenables API Spec fetched from SwaggerHub.
Updates the Spec to the Fabric 4.7 API spec (revising necessary patches).

In addition to new objects and properties, its worth noting that Git detected the following (potential) resource renames:

```
 docs/{AnyOfRoutingProtocolBase.md => AnyOfFabricGatewayFilter.md}                                            |     2 +-
 docs/{AnyOfNetworkFilter.md => BgpActionStates.md}                                                           |     2 +-
 docs/{ResourceType.md => BgpActions.md}                                                                      |     2 +-
 docs/{FilterResponse.md => BgpActionsBulkData.md}                                                            |     4 +-
 docs/{VirtualGateway.md => FabricGateway.md}                                                                 |     7 +-
 docs/{VirtualGatewayChangeOperation.md => FabricGatewayChangeOperation.md}                                   |     2 +-
 docs/{VirtualGatewayFilter.md => FabricGatewayFilter.md}                                                     |     2 +-
 docs/{VirtualGatewayPackageType.md => FabricGatewayPackageType.md}                                           |     2 +-
 docs/{VirtualGatewayPostRequest.md => FabricGatewayPostRequest.md}                                           |     4 +-
 docs/{VirtualGatewaySearchRequest.md => FabricGatewaySearchRequest.md}                                       |     6 +-
 docs/{VirtualGatewaySimpleExpression.md => FabricGatewaySimpleExpression.md}                                 |     2 +-
 docs/{VirtualGatewaySortBy.md => FabricGatewaySortBy.md}                                                     |     2 +-
 docs/{AnyOfVirtualGatewayFilter.md => FabricGatewaySortDirection.md}                                         |     2 +-
 docs/{ValidateByAuthKeyPostRequestFilter.md => LinkProtocolConnection.md}                                    |     7 +-
 docs/{AllPhysicalPortsResponse.md => LinkProtocolGetResponse.md}                                             |     4 +-
 docs/{AnyOfRoutingProtocolData.md => OneOfRoutingProtocolBase.md}                                            |     2 +-
 docs/{VirtualGatewayFilters.md => ServiceTokenSearchRequest.md}                                              |     5 +-
 docs/{ValidateByAuthKeyPostRequestFilterAnd.md => ValidateConnectionRequestFilterAnd.md}                     |     2 +-
 fabric/v4/{api_filters.go => api_health.go}                                                                  |    50 +-
 fabric/v4/{model_any_of_network_filter.go => model_bgp_action_request.go}                                    |     8 +-
 fabric/v4/{model_virtual_gateway_sort_direction.go => model_bgp_action_states.go}                            |    13 +-
 fabric/v4/{model_resource_type.go => model_bgp_actions.go}                                                   |    19 +-
```

The following deletions should also be called out (these are potential, as they may have been renamed, especially following the above patterns):
```
	deleted:    docs/BulkPhysicalPort.md
	deleted:    docs/BulkPort.md
	deleted:    docs/ConnectionBulk.md
	deleted:    docs/ConnectionBulkPostRequest.md
	deleted:    docs/ConnectionIpv4.md
	deleted:    docs/EventsApi.md
	deleted:    docs/Filter.md
	deleted:    docs/FiltersApi.md
	deleted:    docs/NetworkFilters.md
	deleted:    docs/NetworkOrFilter.md
	deleted:    docs/NetworkSimpleExpression.md
	deleted:    docs/PortLag.md
	deleted:    docs/RoutingProtocol.md
	deleted:    docs/RoutingProtocolBgp.md
	deleted:    docs/RoutingProtocolCustomerRoutes.md
	deleted:    docs/RoutingProtocolDirect.md
	deleted:    docs/RoutingProtocolStatic.md
	deleted:    docs/ValidateByAuthKeyPostRequest.md
	deleted:    docs/ValidateByAuthKeyPostRequestPagination.md
	deleted:    docs/ValidateByAuthKeyPostRequestSort.md
	deleted:    docs/VirtualGatewayAccessPointState.md
	deleted:    docs/VirtualGatewayOrFilter.md
	deleted:    docs/VirtualGatewayPackage.md
	deleted:    docs/VirtualGatewaySortCriteria.md
	deleted:    docs/VirtualGatewaySortDirection.md
	deleted:    fabric/v4/api_events.go
	deleted:    fabric/v4/model_bulk_physical_port.go
	deleted:    fabric/v4/model_bulk_port.go
	deleted:    fabric/v4/model_connection_bulk.go
	deleted:    fabric/v4/model_connection_bulk_post_request.go
	deleted:    fabric/v4/model_connection_ipv4.go
	deleted:    fabric/v4/model_filter.go
	deleted:    fabric/v4/model_filter_response.go
	deleted:    fabric/v4/model_network_simple_expression.go
	deleted:    fabric/v4/model_port_lag.go
	deleted:    fabric/v4/model_routing_protocol.go
	deleted:    fabric/v4/model_routing_protocol_bgp.go
	deleted:    fabric/v4/model_routing_protocol_customer_routes.go
	deleted:    fabric/v4/model_routing_protocol_direct.go
	deleted:    fabric/v4/model_routing_protocol_static.go
	deleted:    fabric/v4/model_validate_by_auth_key_post_request_pagination.go
	deleted:    fabric/v4/model_validate_by_auth_key_post_request_sort.go
	deleted:    fabric/v4/model_virtual_gateway_filters.go
	deleted:    fabric/v4/model_virtual_gateway_or_filter.go
	deleted:    fabric/v4/model_virtual_gateway_package.go
	deleted:    fabric/v4/model_virtual_gateway_sort_by.go
	```

### CODE REVIEW

**Comment by ctreatma** [comment]
It doesn't appear that the deleted items are things that were renamed.  Can we get confirmation from the Fabric team that the things that were deleted are no longer supported in the API?  For example, support for [POST requests to `/fabric/v4/connections/bulk`](https://github.com/equinix-labs/fabric-go/pull/11/files#diff-f1ed731dd5f045b58da6a804b7363323bfbd153f6559a0d9a5ee17c7fb5a5c95L9) appears to have been removed; does that mean that, even if I use the previous release of `fabric-go`, I can't use that endpoint because it no longer exists?

**Comment by manu-equinix** [comment]
> It doesn't appear that the deleted items are things that were renamed. Can we get confirmation from the Fabric team that the things that were deleted are no longer supported in the API? For example, support for [POST requests to `/fabric/v4/connections/bulk`](https://github.com/equinix-labs/fabric-go/pull/11/files#diff-f1ed731dd5f045b58da6a804b7363323bfbd153f6559a0d9a5ee17c7fb5a5c95L9) appears to have been removed; does that mean that, even if I use the previous release of `fabric-go`, I can't use that endpoint because it no longer exists?

As of Fabric API version 4.7, bulk connection creation has been removed.  The idea is to have the API calling client handle the bulk creations. The release notes for each release can be found here - https://developer.equinix.com/docs.

**Comment by displague** [comment]
Direct link: https://developer.equinix.com/dev-docs/fabric/release-notes/april-2023

**Review by ctreatma — APPROVED** [review]

**Comment by ctreatma** [comment]
As far as I can tell, the spec accurately reflects the API, so I'm approving this PR within that scope.  My understanding is that the removed endpoints don't exist any more (i.e., a client using a previous release of this SDK, based on the 4.3 spec, would get a 404 for those endpoints).  I have some concerns about removing endpoints in a minor release, but the API is already released so SDK support for those endpoints is irrelevant.

**Comment by displague** [comment]
> I have some concerns about removing endpoints in a minor release, ...

We are still in v0, so according to https://go.dev/doc/modules/release-workflow:

> After your v0 version is published, you can (and should!) continue to release new versions of it.
> These new versions might include bug fixes (patch releases), additions to the module’s public API (minor releases), and even breaking changes. Because a v0 release makes no guarantees of stability or backward compatibility, you can make breaking changes in its versions.

**Pull request merged**
